"""
FraudMesh AI - SQLAlchemy Models
Database models for fraud detection system
"""

from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, ForeignKey, Text, Index, Enum
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
import enum
from datetime import datetime

Base = declarative_base()


class TransactionStatus(enum.Enum):
    completed = "completed"
    pending = "pending"
    failed = "failed"
    declined = "declined"


class FraudSeverity(enum.Enum):
    low = "low"
    medium = "medium"
    high = "high"
    critical = "critical"


class InvestigationStatus(enum.Enum):
    open = "open"
    in_progress = "in_progress"
    resolved = "resolved"
    escalated = "escalated"


class Merchant(Base):
    """Merchant table"""
    __tablename__ = "merchants"

    merchant_id = Column(String(20), primary_key=True)
    name = Column(String(100), nullable=False)
    category = Column(String(50))
    risk_level = Column(String(20), default="low")
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    transactions = relationship("Transaction", back_populates="merchant")


class Customer(Base):
    """Customer table"""
    __tablename__ = "customers"

    customer_id = Column(String(20), primary_key=True)
    email = Column(String(100), unique=True, nullable=False)
    name = Column(String(100))
    created_at = Column(DateTime, default=datetime.utcnow)
    risk_score = Column(Integer, default=0)

    # Relationships
    accounts = relationship("Account", back_populates="customer")
    payment_instruments = relationship("PaymentInstrument", back_populates="customer")


class Account(Base):
    """Account table"""
    __tablename__ = "accounts"

    account_id = Column(String(20), primary_key=True)
    customer_id = Column(String(20), ForeignKey("customers.customer_id"))
    account_type = Column(String(50))
    status = Column(String(20), default="active")
    created_at = Column(DateTime, default=datetime.utcnow)
    balance = Column(Float, default=0.0)

    # Relationships
    customer = relationship("Customer", back_populates="accounts")
    transactions = relationship("Transaction", back_populates="account")


class Device(Base):
    """Device table"""
    __tablename__ = "devices"

    device_id = Column(String(20), primary_key=True)
    type = Column(String(50))
    os = Column(String(50))
    browser = Column(String(50))
    fingerprint = Column(String(100), unique=True)
    is_rooted = Column(Boolean, default=False)
    is_emulator = Column(Boolean, default=False)

    # Relationships
    transactions = relationship("Transaction", back_populates="device")


class PaymentInstrument(Base):
    """Payment instrument table"""
    __tablename__ = "payment_instruments"

    payment_instrument_id = Column(String(20), primary_key=True)
    customer_id = Column(String(20), ForeignKey("customers.customer_id"))
    type = Column(String(50))
    last_four = Column(String(4))
    network = Column(String(20))
    is_prepaid = Column(Boolean, default=False)
    is_virtual = Column(Boolean, default=False)
    is_issuing_country_high_risk = Column(Boolean, default=False)

    # Relationships
    customer = relationship("Customer", back_populates="payment_instruments")


class Transaction(Base):
    """Transaction table"""
    __tablename__ = "transactions"

    transaction_id = Column(String(20), primary_key=True)
    merchant_id = Column(String(20), ForeignKey("merchants.merchant_id"))
    customer_id = Column(String(20))
    account_id = Column(String(20), ForeignKey("accounts.account_id"))
    device_id = Column(String(20), ForeignKey("devices.device_id"))
    ip_address = Column(String(45))
    payment_instrument_id = Column(String(20))
    amount = Column(Float, nullable=False)
    timestamp = Column(DateTime, default=datetime.utcnow)
    status = Column(String(20), default="pending")
    is_fraudulent = Column(Boolean, default=False)
    fraud_ring_id = Column(String(20), nullable=True)

    # Relationships
    merchant = relationship("Merchant", back_populates="transactions")
    account = relationship("Account", back_populates="transactions")
    device = relationship("Device", back_populates="transactions")
    fraud_signals = relationship("FraudSignal", back_populates="transaction")

    # Indexes for common queries
    __table_args__ = (
        Index("idx_transactions_account_id", "account_id"),
        Index("idx_transactions_customer_id", "customer_id"),
        Index("idx_transactions_device_id", "device_id"),
        Index("idx_transactions_timestamp", "timestamp"),
        Index("idx_transactions_status", "status"),
        Index("idx_transactions_is_fraudulent", "is_fraudulent"),
    )


class FraudSignal(Base):
    """Fraud signals generated by detection rules"""
    __tablename__ = "fraud_signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    transaction_id = Column(String(20), ForeignKey("transactions.transaction_id"))
    signal_type = Column(String(100), nullable=False)
    signal_value = Column(String(255))
    score_contribution = Column(Float, default=0.0)
    description = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    transaction = relationship("Transaction", back_populates="fraud_signals")


class Investigation(Base):
    """Fraud investigations"""
    __tablename__ = "investigations"

    investigation_id = Column(String(20), primary_key=True)
    transaction_id = Column(String(20))
    status = Column(String(20), default="open")
    priority = Column(String(20), default="medium")
    assigned_to = Column(String(100))
    notes = Column(Text)
    resolution = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Indexes
    __table_args__ = (
        Index("idx_investigations_status", "status"),
        Index("idx_investigations_transaction_id", "transaction_id"),
    )


class IpAddress(Base):
    """IP address data"""
    __tablename__ = "ip_addresses"

    ip_address = Column(String(45), primary_key=True)
    country = Column(String(10))
    is_vpn = Column(Boolean, default=False)
    is_proxy = Column(Boolean, default=False)
    is_datacenter = Column(Boolean, default=False)
    risk_score = Column(Integer, default=0)


class FraudRing(Base):
    """Fraud ring definitions"""
    __tablename__ = "fraud_rings"

    ring_id = Column(String(20), primary_key=True)
    name = Column(String(100), nullable=False)
    description = Column(Text)
    pattern = Column(String(100))
    severity = Column(String(20), default="medium")
    accounts_json = Column(Text)  # JSON array of account IDs
    devices_json = Column(Text)   # JSON array of device IDs
    ip_addresses_json = Column(Text)  # JSON array of IP addresses
    merchants_json = Column(Text)  # JSON array of merchant IDs
    created_at = Column(DateTime, default=datetime.utcnow)